### ISSUE TITLE
Unable to reproduce

### ISSUE THREAD

**Issue by botaoye** [Jasonkks/PTTR#3]
Hi, thanks for your work. I try to train the Kitti Cyclist model with your code using the default training setting (160 epochs with batch size 64), but the performance of the last epoch (58.0/78.9) is largely behind the result in your paper (65.1 / 90.5). So I wonder if there are any tricks or common practices to picking the model (e.g. finding the model with the best performance rather than the model of the last epoch)?

**Comment by Jasonkks** [comment]
Hi, thanks for your interest. I reran the training and testing, but it seems that I do not encounter the issue you mentioned. There might be some fluctuations in performance, but the gap you mentioned is not common from my experience. I have attached the train/test log and the checkpoint for your reference at [link](https://drive.google.com/file/d/1zgDMBCE-NBH0SDijCN067-VkP-eog-yR/view?usp=sharing).

**Comment by SP-FA** [comment]
> Hi, thanks for your work. I try to train the Kitti Cyclist model with your code using the default training setting (160 epochs with batch size 64), but the performance of the last epoch (58.0/78.9) is largely behind the result in your paper (65.1 / 90.5). So I wonder if there are any tricks or common practices to picking the model (e.g. finding the model with the best performance rather than the model of the last epoch)?


Hi, sorry to bother you. Have you successfully reproduced the results? When training the KITTI Pedestrian model, the best performance I achieved was a Success rate of 45.0, which is lower than the 50.9 reported in the paper. How did you solve this issue?

Environment:
GPU: RTX 4090D
Ubuntu: 20.04
Python:  3.8
Cuda : 11.8
torch: 1.7.0
